In [1]:
import torch

import os
import sys
sys.path.append(os.path.abspath(".."))

from ase import Atoms
from ase.visualize import view
from ase.units import GPa
from ase.spacegroup import crystal

from mattersim.forcefield.potential import Potential
from mattersim.forcefield.potential import MatterSimCalculator
from mattersim.applications.relax import Relaxer
from mattersim.applications.moldyn import MolecularDynamics

from utils.visualisation import plot_potential, plot_relaxation, visualise_structure

from ase.visualize import view

Molecular Dynamics simulation only accept ase atoms with an attached calculator.

*Args:*
- atoms (Union[Atoms, Structure]): ASE atoms object contains structure information and calculator.
- ensemble (str, optional): Simulation ensemble choosen. Defaults to nvt_nose_hoover'
- temperature (float, optional): Simulation temperature, in Kelvin. Defaults to 300 K.
- timestep (float, optional): The simulation time step, in fs. Defaults to 1 fs.
- taut (float, optional): Characteristic timescale of the thermostat, in fs. If is None, automatically set it to 1000 * timestep.
- trajectory (Union[str, Trajectory], optional): Attach trajectory object. If trajectory is a string a Trajectory will be constructed. Defaults to None, which means for no trajectory.
- logfile (str, optional): If logfile is a string, a file with that name will be opened. Defaults to '-', which means output to stdout.
- loginterval (int, optional): Only write a log line for every loginterval time steps. Defaults to 10.
- append_trajectory (bool, optional): If False the trajectory file to be overwriten each time the dynamics is restarted from scratch. If True, the new structures are appended to the trajectory file instead.


In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"MatterSim running on {device}")

MatterSim running on cpu


In [3]:
model = 5

In [4]:
# Define the L1₀ unit cell parameters
a = 3.85  # Lattice constant in x and y
c = 3.72  # Lattice constant in z (slightly compressed)

# Define the atomic positions and symbols
positions = [
    (0, 0, 0),               # Fe atom
    (0.5 * a, 0.5 * a, 0.5 * c),  # Pt atom
]

symbols = ['Fe', 'Pt']

# Create the unit cell for L1₀ FePt
structure = Atoms(symbols="FePt",
                 positions=positions,
                 cell=[(a, 0, 0), (0, a, 0), (0, 0, c)],
                 pbc=True)  # Periodic boundary conditions

In [5]:
_ = visualise_structure(structure)

Structure positions: [[0.    0.    0.   ]
 [1.925 1.925 1.86 ]]


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [6]:
view(structure, viewer='x3d')

In [7]:
structure.positions

array([[0.   , 0.   , 0.   ],
       [1.925, 1.925, 1.86 ]])

In [8]:
structure.calc = MatterSimCalculator(load_path=f"MatterSim-v1.0.0-{model}M.pth", device=device)

2025-02-06 02:58:36.520 | INFO     | mattersim.forcefield.potential:from_checkpoint:891 - Loading the pre-trained mattersim-v1.0.0-5M.pth model


/usr/local/lib/python3.12/dist-packages/mattersim/forcefield/potential.py:896: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(load_path, map_location=

In [9]:
print(f"Energy (eV)                 = {structure.get_potential_energy()}")
print(f"Energy per atom (eV/atom)   = {structure.get_potential_energy()/len(structure)}")
print(f"Forces of first atom (eV/A) = {structure.get_forces()[0]}")
print(f"Stress[0][0] (x-x) (eV/A^3) = {structure.get_stress(voigt=False)[0][0]}")
print(f"Stress[0][0] (x-x) (GPa)    = {structure.get_stress(voigt=False)[0][0] / GPa}")

Energy (eV)                 = -10.912311553955078
Energy per atom (eV/atom)   = -5.456155776977539
Forces of first atom (eV/A) = [1.2665987e-06 9.8347664e-07 2.2351742e-08]
Stress[0][0] (x-x) (eV/A^3) = 0.13285755648978012
Stress[0][0] (x-x) (GPa)    = 21.2861270904541


In [10]:
structure.cell.cellpar()

array([ 3.85,  3.85,  3.72, 90.  , 90.  , 90.  ])

In [11]:
trajectory_file = "md_trajectory.traj"
log_file = "md_simulation.log"

In [12]:
md = MolecularDynamics(
    atoms=structure,
    ensemble="nvt_nose_hoover",
    # ensemble = "nvt_berendsen",
    temperature=300,
    timestep=1.0,
    loginterval=10,
    logfile = log_file,
    trajectory=trajectory_file  # Save trajectory
)

In [13]:
md.run(n_steps=1000)

In [14]:
md.atoms.cell.cellpar()

array([ 3.85,  3.85,  3.72, 90.  , 90.  , 90.  ])

In [15]:
md.atoms.get_positions()

array([[-0.24625245, -2.93173314,  1.89404292],
       [ 1.99549244,  2.76424174,  1.31780885]])

In [16]:
print(f"Energy (eV)                 = {md.atoms.get_potential_energy()}")
print(f"Energy per atom (eV/atom)   = {md.atoms.get_potential_energy()/len(structure)}")
print(f"Forces of first atom (eV/A) = {md.atoms.get_forces()[0]}")
print(f"Stress[0][0] (x-x) (eV/A^3) = {md.atoms.get_stress(voigt=False)[0][0]}")
print(f"Stress[0][0] (x-x) (GPa)    = {md.atoms.get_stress(voigt=False)[0][0] / GPa}")

Energy (eV)                 = -11.721893310546875
Energy per atom (eV/atom)   = -5.8609466552734375
Forces of first atom (eV/A) = [-0.17170045 -0.04480059 -0.26473644]
Stress[0][0] (x-x) (eV/A^3) = 0.11457430188352528
Stress[0][0] (x-x) (GPa)    = 18.356826782226562


In [17]:
_ = visualise_structure(md.atoms)

Structure positions: [[-0.24625245 -2.93173314  1.89404292]
 [ 1.99549244  2.76424174  1.31780885]]


3Dmol.js failed to load for some reason. Please check your browser console for error messages.